### ISSUE TITLE
get_related_resource_type returns parent model name

### ISSUE THREAD

**Issue by martinmaillard** [django-json-api/django-rest-framework-json-api#77]
This is a simplified version of my API:

    class Survey(models.Model):
        pass

    class Question(models.Model):
        survey = models.ForeignKey(Survey, related_name='questions')

    class SurveySerializer(serializers.ModelSerializer):
        class Meta:
            model = Survey
            fields = ('id', 'questions')
            read_only_fields = ('questions',)

    class SurveyViewSet(viewsets.ModelViewSet):
         queryset = Survey.objects.all()
         serializer_class = SurveySerializer

Now if I request a survey, the type of the questions is not correct :

    >>> GET '/surveys/1'
    {
        'data': {
            'id': '1',
            'type': 'surveys',
            'attributes': {},
            'relationships': {
                'questions': {
                    'data': [
                        {
                            'id': '1',
                            'type': 'surveys',
                            'attributes': {},
                        },
                    ],
                },
            },
        },
    }

The issue seems to be in `utils.get_related_resource_type`. I would submit a PR, but I'm not entirely sure how to fix it without breaking something else...

Also, I'm guessing that it will be necessary to be able to define a `resource_name` for related models and the relationships handling code will change, but this is still a big issue.

**Comment by jsenecal** [comment]
Pull latest version from github, I fixed that I think in some commit.

On Sep 14, 2015 10:11 AM, Martin Maillard <notifications@github.com> wrote:

This is a simplified version of my API:

class Survey(models.Model):
    pass

class Question(models.Model):
    survey = models.ForeignKey(Survey, related_name='questions')

class SurveySerializer(serializers.ModelSerializer):
    class Meta:
        model = Survey
        fields = ('id', 'questions')
        read_only_fields = ('questions',)

class SurveyViewSet(viewsets.ModelViewSet):
     queryset = Survey.objects.all()
     serializer_class = SurveySerializer


Now if I request a survey, the type of the questions is not correct :

>>> GET '/surveys/1'
{
    'data': {
        'id': '1',
        'type': 'survey',
        'attributes': {},
        'relationships': {
            'questions': {
                'data': [
                    {
                        'id': '1',
                        'type': 'survey',
                        'attributes': {},
                    },
                ],
            },
        },
    },
}


The issue seems to be in utils.get_related_resource_type. I would submit a PR, but I'm not entirely sure how to fix it without breaking something else...

Also, I'm guessing that it will be necessary to be able to define a resource_name for related models and the relationships handling code will change, but this is still a big issue.

**Comment by martinmaillard** [comment]
Thanks for the quick reply! I upgraded to the latest commit on "develop" and the problem is still happening...

**Comment by jsenecal** [comment]
Yes you are right, I couldn't see the whole picture from my cellphone. The `get_related_resource_type` method is hoping to be intelligent and tries to find the related name from the field name when everything else fails.

We are going to refactor this to be able to define a `resouce_name` as you suggested.

**Comment by jsenecal** [comment]
Actually, the more I read it the more I thing the behavior is the right one - Model 'survey' is referencing to the  same model. so the relation model is in fact `survey` as well. Unless I misread your code...

**Comment by martinmaillard** [comment]
The records in the `questions` relationship should have the type `questions`, not `surveys`.

**Comment by jsenecal** [comment]
Oups - yes you are right - sry

**Comment by mkohram** [comment]
#74 should be merged with this.

**Comment by jerel** [comment]
This should be fixed by 64f8a6b, if it doesn't resolve your issue I'll reopen.

**Comment by martinmaillard** [comment]
The proper model is now used, but the first letter is a capital, which is probably not intended ?

    >>> GET '/surveys/1'
    {
        'data': {
            ...
            'relationships': {
                'questions': {
                    'data': [
                        {
                            'id': '1',
                            'type': 'Questions',
                            'attributes': {},
                        },
                    ],
                },
            },
        },
    }

**Comment by jsenecal** [comment]
@martinmaillard I noticed that behavior as well, I think this was introduced in commit https://github.com/django-json-api/django-rest-framework-json-api/commit/eeab4607a15960e0d784c1129dbfa7830b35b1c7 altough I would like @schtibe to comment on this as he might have done this on purpose

**Comment by schtibe** [comment]
@jsenecal Yes and no. Actually, with this commit it would've been underscored (which wouldn't be the correct behaviour as well I guess?) Commit 5b6456763ed7cdd51660d5293b66cd899bee7a91 then removed the default underscore behaviour without introducing the lowercase-ing again.
Pull Request #92 wouldn't fix that either, just re-introduce the underscores in case JSON_API_FORMAT_RELATION_KEYS is set. 
I think we have to talk about the default behaviour when JSON_API_FORMAT_RELATION_KEYS is not set.

**Comment by schtibe** [comment]
@martinmaillard FYI there is a new option to format these keys: https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/docs/usage.md#relationship-types

**Comment by martinmaillard** [comment]
That's great ! Thank you !

Now I'm gonna be really annoying, but in my actual use case, my `questions` relationship is polymorphic. Each instance can have a different type subclassing `Question` (`GreatQuestion`, `SuperQuestion`). I think the whole point of specifying the type of each record in json-api is to support this kind of use case. So for `ManyRelatedField` and `ListSerializer`, the `relation_type` should probably be extracted for each instance, instead of once for the whole collection. What do you think ? Do you want me to make a PR so we can discuss on actual code ?

**Comment by jerel** [comment]
That sounds like a valid use case. I would welcome a PR so we can discuss it further

**Comment by martinmaillard** [comment]
I submitted a PR: https://github.com/django-json-api/django-rest-framework-json-api/pull/94
